const testData = [
  {
    no: 1,
    testName: "THYROID FUNCTION TEST (TFT)",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 450,
  },
  {
    no: 2,
    testName: "TSH (Thyroid Stimulating Hormone)",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 250,
  },
  {
    no: 3,
    testName: "Total T3",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 250,
  },
  {
    no: 4,
    testName: "Total T4",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 250,
  },
  {
    no: 5,
    testName: "FT3 FT4 TSH",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 650,
  },
  {
    no: 6,
    testName: "25 OH-Vitamin D/ VIT D3",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 1200,
  },
  {
    no: 7,
    testName: "Hba1c (Whole Blood)",
    sampleType: "EDTA BLOOD",
    volume: "2ml",
    sampleMode: "NON FASTING",
    mrp: 500,
  },
  {
    no: 8,
    testName: "LH + FSH + PRL",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 1400,
  },
  {
    no: 9,
    testName: "CBC - Complete Blood Count",
    sampleType: "EDTA BLOOD",
    volume: "2ml",
    sampleMode: "NON FASTING",
    mrp: 200,
  },
  {
    no: 10,
    testName: "CBC with PS For Opinion",
    sampleType: "EDTA BLOOD",
    volume: "2ml",
    sampleMode: "NON FASTING",
    mrp: 350,
  },
  {
    no: 11,
    testName: "Free T3",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 250,
  },
  {
    no: 12,
    testName: "Free T4",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 250,
  },
  {
    no: 13,
    testName: "Vitamin B12",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 600,
  },
  {
    no: 14,
    testName: "ANA",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 600,
  },
  {
    no: 15,
    testName: "Anti CCP (ACCP)",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 900,
  },
  {
    no: 16,
    testName: "Homocysteine",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 1100,
  },
  {
    no: 17,
    testName: "PSA –Total",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 500,
  },
  {
    no: 18,
    testName: "Insulin Fasting",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "FASTING",
    mrp: 550,
  },
  {
    no: 19,
    testName: "Beta HCG",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 500,
  },
  {
    no: 20,
    testName: "Follicle Stimulating Hormone (FSH)",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 450,
  },
  // {
  //   no: 20,
  //   testName: "Follicle Stimulating Hormone (FSH)",
  //   sampleType: "SERUM",
  //   volume: "1ml",
  //   sampleMode: "NON FASTING",
  //   mrp: 450,
  // },
  {
    no: 20,
    testName: "Follicle Stimulating Hormone (FSH)",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 450,
  },
  {
    no: 20,
    testName: "Follicle Stimulating Hormone (FSH)",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 450,
  },
  {
    no: 20,
    testName: "Follicle Stimulating Hormone (FSH)",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 450,
  },
  {
    no: 20,
    testName: "Follicle Stimulating Hormone (FSH)",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 450,
  },
  {
    no: 20,
    testName: "Follicle Stimulating Hormone (FSH)",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 450,
  },
  {
    no: 20,
    testName: "Follicle Stimulating Hormone (FSH)",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 450,
  },
  {
    no: 20,
    testName: "Follicle Stimulating Hormone (FSH)",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 450,
  },
  {
    no: 20,
    testName: "Follicle Stimulating Hormone (FSH)",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 450,
  },
  {
    no: 20,
    testName: "Follicle Stimulating Hormone (FSH)",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 450,
  },
  {
    no: 20,
    testName: "Follicle Stimulating Hormone (FSH)",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 450,
  },
  {
    no: 20,
    testName: "Follicle Stimulating Hormone (FSH)",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 450,
  },
  {
    no: 20,
    testName: "Follicle Stimulating Hormone (FSH)",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 450,
  },
  {
    no: 20,
    testName: "Follicle Stimulating Hormone (FSH)",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 450,
  },
  {
    no: 20,
    testName: "Follicle Stimulating Hormone (FSH)",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 450,
  },
  {
    no: 20,
    testName: "Follicle Stimulating Hormone (FSH)",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 450,
  },
  {
    no: 20,
    testName: "Follicle Stimulating Hormone (FSH)",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 450,
  },
  {
    no: 20,
    testName: "Follicle Stimulating Hormone (FSH)",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 450,
  },
  {
    no: 20,
    testName: "Follicle Stimulating Hormone (FSH)",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 450,
  },
  {
    no: 20,
    testName: "Follicle Stimulating Hormone (FSH)",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 450,
  },
  {
    no: 20,
    testName: "Follicle Stimulating Hormone (FSH)",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 450,
  },
  {
    no: 20,
    testName: "Follicle Stimulating Hormone (FSH)",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 450,
  },
  {
    no: 20,
    testName: "Follicle Stimulating Hormone (FSH)",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 450,
  },
];

export default testData;
