const testData = [
  {
    no: 1,
    testName: "THYROID FUNCTION TEST (TFT)",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 450,
  },
  {
    no: 2,
    testName: "TSH (Thyroid Stimulating Hormone)",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 250,
  },
  {
    no: 3,
    testName: "Total T3",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 250,
  },
  {
    no: 4,
    testName: "Total T4",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 250,
  },
  {
    no: 5,
    testName: "FT3 FT4 TSH",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 650,
  },
  {
    no: 6,
    testName: "25 OH-Vitamin D/ VIT D3",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 1200,
  },
  {
    no: 7,
    testName: "Hba1c (Whole Blood)",
    sampleType: "EDTA BLOOD",
    volume: "2ml",
    sampleMode: "NON FASTING",
    mrp: 500,
  },
  {
    no: 8,
    testName: "LH + FSH + PRL",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 1400,
  },
  {
    no: 9,
    testName: "CBC - Complete Blood Count",
    sampleType: "EDTA BLOOD",
    volume: "2ml",
    sampleMode: "NON FASTING",
    mrp: 200,
  },
  {
    no: 10,
    testName: "CBC with PS For Opinion",
    sampleType: "EDTA BLOOD",
    volume: "2ml",
    sampleMode: "NON FASTING",
    mrp: 350,
  },
  {
    no: 11,
    testName: "Free T3",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 250,
  },
  {
    no: 12,
    testName: "Free T4",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 250,
  },
  {
    no: 13,
    testName: "Vitamin B12",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 600,
  },
  {
    no: 14,
    testName: "ANA",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 600,
  },
  {
    no: 15,
    testName: "Anti CCP (ACCP)",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 900,
  },
  {
    no: 16,
    testName: "Homocysteine",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 1100,
  },
  {
    no: 17,
    testName: "PSA –Total",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 500,
  },
  {
    no: 18,
    testName: "Insulin Fasting",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "FASTING",
    mrp: 550,
  },
  {
    no: 19,
    testName: "Beta HCG",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 500,
  },
  {
    no: 20,
    testName: "Follicle Stimulating Hormone (FSH)",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 450,
  },
  {
    no: 21,
    testName: "Prolactin",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 450,
  },
  {
    no: 25,
    testName: "Total IGE",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 600,
  },
  {
    no: 26,
    testName: "Ferritin",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 550,
  },
  {
    no: 27,
    testName: "CA-125",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 800,
  },
  {
    no: 28,
    testName: "CA 19.9",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 800,
  },
  {
    no: 29,
    testName: "CA15.3",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 800,
  },
  {
    no: 30,
    testName: "CEA",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 600,
  },
  {
    no: 31,
    testName: "AMH",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 1500,
  },
  {
    no: 32,
    testName: "PTH - Intact (Parathyroid Hormone)",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 1000,
  },
  {
    no: 33,
    testName: "AFP",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 550,
  },
  {
    no: 34,
    testName: "Progesterone",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 800,
  },
  {
    no: 35,
    testName: "17 OH Progesterone",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 850,
  },
  {
    no: 36,
    testName: "Creatinine",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 100,
  },
  {
    no: 37,
    testName: "Beta Thalassemia Screening",
    sampleType: "EDTA BLOOD",
    volume: "2ml",
    sampleMode: "NON FASTING",
    mrp: 800,
  },
  {
    no: 38,
    testName: "Beta 2 Glycoprotein 1 - Igm",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 550,
  },
  {
    no: 39,
    testName: "Beta 2 Glycoprotein 1 - Igg",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 550,
  },
  {
    no: 40,
    testName: "Microalbumin",
    sampleType: "URINE",
    volume: "2ml",
    sampleMode: "RANDOM SAMPLE",
    mrp: 500,
  },
  {
    no: 41,
    testName: "Amylase",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 400,
  },
  {
    no: 42,
    testName: "Lipase",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 500,
  },
  {
    no: 43,
    testName: "Uric Acid",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 200,
  },
  {
    no: 44,
    testName: "CRP",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 450,
  },
  {
    no: 45,
    testName: "Calcium",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 160,
  },
  {
    no: 46,
    testName: "Anti TPO/ AMA",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 1500,
  },
  {
    no: 47,
    testName: "BUN",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 150,
  },
  {
    no: 48,
    testName: "ToxoGondii – IGG",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 250,
  },
  {
    no: 49,
    testName: "ToxoGondii - IGM",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 250,
  },
  {
    no: 50,
    testName: "Herpes Simplex Virus (HSV) - IGG",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 250,
  },
  {
    no: 51,
    testName: "Herpes Simplex Virus (HSV) - IGM",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 250,
  },
  {
    no: 52,
    testName: "Rubella – IGG",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 250,
  },
  {
    no: 53,
    testName: "Rubella – IGM",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 250,
  },
  {
    no: 54,
    testName: "Cytomegalo Virus (CMV) - IGG",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 250,
  },
  {
    no: 55,
    testName: "Cytomegalo Virus (CMV) - IGM",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 250,
  },
  {
    no: 56,
    testName: "Herpes Simplex Virus I (HSV)-IGG",
    sampleType: "SERUM",
    volume: "2 ml",
    sampleMode: "NON FASTING",
    mrp: 250,
  },
  {
    no: 57,
    testName: "Herpes Simplex Virus I (HSV)-IGM",
    sampleType: "SERUM",
    volume: "2 ml",
    sampleMode: "NON FASTING",
    mrp: 250,
  },
  {
    no: 58,
    testName: "Herpes Simplex Virus II (HSV)-IGG",
    sampleType: "SERUM",
    volume: "2 ml",
    sampleMode: "NON FASTING",
    mrp: 250,
  },
  {
    no: 59,
    testName: "Herpes Simplex Virus II (HSV)-IGM",
    sampleType: "SERUM",
    volume: "2 ml",
    sampleMode: "NON FASTING",
    mrp: 250,
  },
  {
    no: 60,
    testName: "RA Factor",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 350,
  },
  {
    no: 61,
    testName: "Estradiol (E2)",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 600,
  },
  {
    no: 62,
    testName: "Sugar (Glucose) Post Prandial",
    sampleType: "FLUORIDE",
    volume: "2ml",
    sampleMode: "NON FASTING",
    mrp: 60,
  },
  {
    no: 63,
    testName: "SGPT",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 120,
  },
  {
    no: 64,
    testName: "SGOT",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 150,
  },
  {
    no: 65,
    testName: "Magnesium",
    sampleType: "SERUM",
    volume: "3ml",
    sampleMode: "NON FASTING",
    mrp: 300,
  },
  {
    no: 66,
    testName: "Phosphorous",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 200,
  },
  {
    no: 67,
    testName: "Lipoprotein (A)",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "FASTING",
    mrp: 950,
  },
  {
    no: 68,
    testName: "Apolipoprotein- A1 (APO-A1)",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "FASTING",
    mrp: 650,
  },
  {
    no: 69,
    testName: "Apolipoprotein-B (APO-B)",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "FASTING",
    mrp: 650,
  },
  {
    no: 70,
    testName: "DHEA’S",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 700,
  },
  {
    no: 71,
    testName: "Folic acid",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 600,
  },
  {
    no: 72,
    testName: "ANTI THYROGLOBULIN ANTIBODY (ATG)",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 700,
  },
  {
    no: 73,
    testName: "THYROGLOBULIN (TG)",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 750,
  },
  {
    no: 74,
    testName: "TISSUE TRANSGLUTAMINASE -IGA (TTG)",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 750,
  },
  {
    no: 75,
    testName: "H Growth Hormone",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 650,
  },
  {
    no: 76,
    testName: "Cortisol",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 600,
  },
  {
    no: 77,
    testName: "Anti-Phospholipid Antibody – IGG (APLG)",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 800,
  },
  {
    no: 78,
    testName: "Anti-Phospholipid Antibody – IGM (APLM)",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 800,
  },
  {
    no: 79,
    testName: "ANTI HEPA B SURFACE AG (HBSAG)",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "NON FASTING",
    mrp: 450,
  },
  {
    no: 80,
    testName: "ANTI HEP B SURFACE AG- TOTAL (HBST)",
    sampleType: "SERUM",
    volume: "1ml",
    sampleMode: "FASTING",
    mrp: 650,
  },
];

export default testData;
